import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--canvas)',
        'surface-1': 'var(--surface-1)',
        'surface-2': 'var(--surface-2)',
        'surface-3': 'var(--surface-3)',
        'surface-4': 'var(--surface-4)',
        hairline: 'var(--hairline)',
        'hairline-strong': 'var(--hairline-strong)',
        'hairline-tertiary': 'var(--hairline-tertiary)',
        ink: 'var(--ink)',
        'ink-muted': 'var(--ink-muted)',
        'ink-subtle': 'var(--ink-subtle)',
        'ink-tertiary': 'var(--ink-tertiary)',
        primary: 'var(--primary)',
        'primary-hover': 'var(--primary-hover)',
        'primary-focus': 'var(--primary-focus)',
        'primary-muted': 'var(--primary-muted)',
        'on-primary': 'var(--on-primary)',
        success: 'var(--success)',
        warning: 'var(--warning)',
        critical: 'var(--critical)',
        maintenance: 'var(--maintenance)',
        unknown: 'var(--unknown)',
        'inverse-canvas': 'var(--inverse-canvas)',
        'inverse-ink': 'var(--inverse-ink)',
      },
      fontFamily: {
        display: ['Inter', 'SF Pro Display', '-apple-system', 'system-ui', 'sans-serif'],
        text: ['Inter', '-apple-system', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.05', fontWeight: '600', letterSpacing: '-3.0px' }],
        'display-lg': ['56px', { lineHeight: '1.10', fontWeight: '600', letterSpacing: '-1.8px' }],
        'display-md': ['40px', { lineHeight: '1.15', fontWeight: '600', letterSpacing: '-1.0px' }],
        headline: ['28px', { lineHeight: '1.20', fontWeight: '600', letterSpacing: '-0.6px' }],
        'card-title': ['22px', { lineHeight: '1.25', fontWeight: '500', letterSpacing: '-0.4px' }],
        subhead: ['20px', { lineHeight: '1.40', fontWeight: '400', letterSpacing: '-0.2px' }],
        'body-lg': ['18px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '-0.1px' }],
        'body-md': ['16px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '-0.05px' }],
        'body-sm': ['14px', { lineHeight: '1.50', fontWeight: '400', letterSpacing: '0' }],
        caption: ['12px', { lineHeight: '1.40', fontWeight: '400', letterSpacing: '0' }],
        button: ['14px', { lineHeight: '1.20', fontWeight: '500', letterSpacing: '0' }],
        eyebrow: ['13px', { lineHeight: '1.30', fontWeight: '500', letterSpacing: '0.4px' }],
      },
      borderRadius: {
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        xxl: '24px',
        pill: '9999px',
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        xxl: '48px',
        section: '96px',
      },
    },
  },
  plugins: [],
} satisfies Config;
